{"name": "Переход в раздел «История заказов»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <tests.test_personal_account.TestPersonalAccount object at 0x10652c820>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"f47a0088-9a08-4d35-83dc-acdae5916776\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"f47a0088-9a08-4d35-83dc-acdae5916776\")>\n\n    @allure.title('Переход в раздел «История заказов»')\n    def test_redirect_to_order_history_section(self, driver, wait): # ВАЛИТСЯ один браузер (Mozilla)\n        redirect_to_order_history_section = PersonalAccountPage(driver, wait)\n        redirect_to_order_history_section.login()\n        redirect_to_order_history_section.click_on_personal_account_button()\n>       redirect_to_order_history_section.wait_loading(redirect_to_order_history_section.get_url())\n\ntests/test_personal_account.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages/base_page.py:42: in wait_loading\n    self.wait.until(lambda driver: url != self.get_url())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f47a0088-9a08-4d35-83dc-acdae5916776\")>, method = <function BasePage.wait_loading.<locals>.<lambda> at 0x1065cd9d0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "steps": [{"name": "Залогиниться", "status": "passed", "start": 1726400465774, "stop": 1726400467067}, {"name": "Тап на кнопку «Личный кабинет»", "status": "passed", "start": 1726400467067, "stop": 1726400467284}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1726400465774, "stop": 1726400482539, "uuid": "82248dd5-99ee-48a1-8e29-6e17f20cb444", "historyId": "40cff52c95abdad43e3b8c55a5fc3199", "testCaseId": "7952af852b02d5ba667c5c5cd9407af2", "fullName": "tests.test_personal_account.TestPersonalAccount#test_redirect_to_order_history_section", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_personal_account"}, {"name": "subSuite", "value": "TestPersonalAccount"}, {"name": "host", "value": "Air--Abusha"}, {"name": "thread", "value": "17784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_personal_account"}]}